- id: '1610593146218'
  alias: BaumAssistant - Set Fan Speed for Argon40
  description: Set fan speed of Argon40 for Raspberry Pi based on numeric value from
    slider
  trigger:
  - platform: state
    entity_id: input_number.argon40_fanspeed
  condition: []
  action:
  - service: argon40.set_fan_speed
    data:
      speed: '{{ states(''input_number.argon40_fanspeed'') }}'
  mode: single
- id: '1611109736952'
  alias: Hue Switch - Wohnzimmer - Licht an
  description: Manuelles einschalten des Lichts im Wohnzimmer (einfacher Druck auf
    Schalter links oben)
  trigger:
  - device_id: 55a523725e38ea18dce62d926333fa77
    domain: deconz
    platform: device
    type: remote_button_short_press
    subtype: button_1
  condition: []
  action:
  - scene: scene.licht_wohnzimmer_warm
  mode: single
- id: '1611109902456'
  alias: Hue Switch - Wohnzimmer - Licht aus
  description: Manuelles ausschalten des Lichts im Wohnzimmer (einfacher Druck auf
    Schalter links unten)
  trigger:
  - device_id: 55a523725e38ea18dce62d926333fa77
    domain: deconz
    platform: device
    type: remote_button_short_press
    subtype: button_2
  condition: []
  action:
  - service: light.turn_off
    data:
      transition: 2
    entity_id: light.wohnzimmer
  mode: single
- id: '1611110148290'
  alias: Hue Switch - Wohnzimmer - Lichtszene 1
  description: Manually active a first living room light scene  - single click of
    both top buttons
  trigger:
  - device_id: 55a523725e38ea18dce62d926333fa77
    domain: deconz
    platform: device
    type: remote_button_short_release
    subtype: top_buttons
  condition: []
  action:
  - scene: scene.licht_wohnzimmer_ambiente_warm
  mode: single
- id: '1611110635997'
  alias: Hue Switch - Wohnzimmer - Lichtszene 2
  description: Manually active a second living room light scene  - single click of
    both bottom buttons
  trigger:
  - device_id: 55a523725e38ea18dce62d926333fa77
    domain: deconz
    platform: device
    type: remote_button_short_release
    subtype: bottom_buttons
  condition: []
  action:
  - scene: scene.licht_wohnzimmer_ambiente_kalt
  mode: single
- id: '1611533571050'
  alias: Hue Switch - Wohnzimmer - Lichtgruppe 1
  description: Manually active a first living room light group  - single click of
    top right button
  trigger:
  - device_id: 55a523725e38ea18dce62d926333fa77
    domain: deconz
    platform: device
    type: remote_button_short_press
    subtype: button_3
  condition: []
  action:
  - scene: scene.licht_wohnzimmer_hell_decke
  mode: single
- id: '1611533789209'
  alias: Hue Switch - Wohnzimmer - Lichtgruppe 2
  description: ''
  trigger:
  - device_id: 55a523725e38ea18dce62d926333fa77
    domain: deconz
    platform: device
    type: remote_button_short_press
    subtype: button_4
  condition: []
  action:
  - scene: scene.licht_wohnzimmer_hell_stehlampe
  mode: restart
- id: '1611534133830'
  alias: Hue Switch - Wohnzimmer - Lichtszene 3
  description: ''
  trigger:
  - device_id: 55a523725e38ea18dce62d926333fa77
    domain: deconz
    platform: device
    type: remote_button_long_press
    subtype: bottom_buttons
  condition: []
  action:
  - scene: scene.licht_wohnzimmer_nacht
  mode: single
- id: '1611535378933'
  alias: Hue Switch - Wohnzimmer - Colorloop
  description: ''
  trigger:
  - device_id: 55a523725e38ea18dce62d926333fa77
    domain: deconz
    platform: device
    type: remote_button_long_press
    subtype: top_buttons
  condition: []
  action:
  - scene: scene.licht_wohnzimmer_ambiente_loop
  mode: single
- id: '1612483646732'
  alias: Licht Eingang - An - Hue Switch
  description: ''
  trigger:
  - device_id: 481c7402cfa0e979560ab8a222c7e464
    domain: deconz
    platform: device
    type: remote_button_short_release
    subtype: button_1
  condition: []
  action:
  - service: scene.turn_on
    data:
      transition: 1
    target:
      entity_id: scene.licht_eingang_warm
  mode: single
- id: '1612484496288'
  alias: Licht Eingang - Aus - Hue Switch
  description: Test
  trigger:
  - device_id: 481c7402cfa0e979560ab8a222c7e464
    domain: deconz
    platform: device
    type: remote_button_short_press
    subtype: button_2
  condition: []
  action:
  - service: light.turn_off
    entity_id: light.eingang, light.treppenhaus, light.flur
    data:
      transition: 1
  mode: single
- id: '1612529119404'
  alias: Notify about phone state
  trigger:
  - platform: state
    entity_id: sensor.fritz_box_6591_cable_kdg_call_monitor_fritzbox_callmonitor
  action:
  - service: notify.persistent_notification
    data:
      title: Phone
      message: "{% if is_state(\"sensor.fritz_box_6591_cable_kdg_call_monitor_fritzbox_callmonitor\"\
        , \"idle\") %}\n  Phone is idle\n{% elif is_state(\"sensor.phfritz_box_6591_cable_kdg_call_monitor_fritzbox_callmonitorone\"\
        , \"dialing\") %}\n  Calling {{ state_attr('sensor.fritz_box_6591_cable_kdg_call_monitor_fritzbox_callmonitor',\
        \ 'to_name') }} ({{ state_attr('sensor.phone', 'to') }})\n{% elif is_state(\"\
        sensor.fritz_box_6591_cable_kdg_call_monitor_fritzbox_callmonitor\", \"ringing\"\
        ) %}\n  Incoming call from {{ state_attr('sensor.fritz_box_6591_cable_kdg_call_monitor_fritzbox_callmonitor',\
        \ 'from_name') }} ({{ state_attr('sensor.phone', 'from') }})\n{% else %}\n\
        \  Talking to {{ state_attr('sensor.fritz_box_6591_cable_kdg_call_monitor_fritzbox_callmonitor',\
        \ 'with_name') }} ({{ state_attr('sensor.phone', 'with') }})\n{% endif %}"
  mode: single
- id: '1612655621849'
  alias: Git - täglicher commit und push der config
  description: Täglicher commit der Änderung und push der config auf das public GitHub
    repo
  trigger:
  - platform: time
    at: '22:00:00'
  condition: []
  action:
  - service: hassio.addon_stdin
    data:
      addon: a0d7b954_ssh
      input: /config/git_push_auto.sh
  mode: single
- id: '1612729623230'
  alias: Licht Schlafzimmer - Ein (Tag) - Hue Control
  description: ''
  trigger:
  - device_id: 00426b488d68b3b7e4ef6392206b0cf4
    domain: deconz
    platform: device
    type: remote_button_short_press
    subtype: turn_on
  - device_id: f3edb7e81afb128c68df358f5922b769
    domain: deconz
    platform: device
    type: remote_button_short_press
    subtype: button_1
  condition:
  - condition: time
    after: '7:00:00'
    before: '22:30:00'
  action:
  - service: scene.turn_on
    data:
      transition: 1
    entity_id: scene.hue_schlafzimmer_hell
  mode: single
- id: '1612729898004'
  alias: Licht Schlafzimmer - Aus - Hue Control
  description: ''
  trigger:
  - device_id: 00426b488d68b3b7e4ef6392206b0cf4
    domain: deconz
    platform: device
    type: remote_button_short_press
    subtype: turn_off
  - device_id: f3edb7e81afb128c68df358f5922b769
    domain: deconz
    platform: device
    type: remote_button_short_press
    subtype: button_2
  condition: []
  action:
  - service: light.turn_off
    data:
      transition: 1
    entity_id: light.schlafzimmer_deckenlicht
  mode: single
- id: '1612730147968'
  alias: Licht Schlafzimmer - Ein (Nacht) - Hue Control
  description: ''
  trigger:
  - device_id: 00426b488d68b3b7e4ef6392206b0cf4
    domain: deconz
    platform: device
    type: remote_button_short_press
    subtype: turn_on
  - device_id: f3edb7e81afb128c68df358f5922b769
    domain: deconz
    platform: device
    type: remote_button_short_press
    subtype: button_1
  condition:
  - condition: time
    after: '22:30:00'
    before: '7:00:00'
  action:
  - service: scene.turn_on
    data:
      transition: 1
    entity_id: scene.hue_schlafzimmer_ambiente
  mode: single
- id: '1613513334468'
  alias: Shopping - Zeige Einkaufsliste
  description: ''
  trigger: []
  condition: []
  action:
  - service: notify.mobile_app_sm_g955f
    data:
      title: Denk an die Einkäufe
      message: Gelange hier zur Einkaufsliste
      data:
        clickAction: /shopping-list
        url: /shopping-list
  mode: single
- id: '1615751487233'
  alias: Hue Switch Eingang - Licht aus BaumHaus
  description: Schaltet das gesamte Licht im BaumHaus aus (z.B. beim Verlassen des
    Hauses)
  trigger:
  - device_id: 481c7402cfa0e979560ab8a222c7e464
    domain: deconz
    platform: device
    type: remote_button_long_press
    subtype: bottom_buttons
  condition: []
  action:
  - service: notify.alexa_media_echo_flex_treppenhaus
    data:
      message: Licht im Haus wird ausgeschaltet
      data:
        type: tts
  - delay: 00:00:20
  - service: light.turn_off
    target:
      entity_id:
      - light.baumhaus
    data:
      transition: 10
  mode: single
- id: '1615751682361'
  alias: New Automation
  description: ''
  trigger:
  - device_id: 481c7402cfa0e979560ab8a222c7e464
    domain: deconz
    platform: device
    type: remote_button_short_press
    subtype: button_3
  condition: []
  action:
  - service: notify.alexa_media_echo_flex_treppenhaus
    data:
      message: Licht wird ausgeschaltet
      data:
        type: tts
  mode: single
- id: '1615934558420'
  alias: FRITZ!Box 6591 - Guest WiFi angeschaltet - Push Login details
  description: ''
  trigger:
  - platform: state
    entity_id: switch.fritzbox_6591_cable_kdg_guest_wifi
    to: 'on'
  condition: []
  action:
  - service: notify.persistent_notification
    data:
      title: BaumHaus-Guest WiFi eingeschaltet
      message: 'WLAN-SSID: BaumHaus-Guest <br> Password: test1234'
  mode: single
- id: '1616796514306'
  alias: SRHH - Push für die morgige Abholung
  description: Benachrichtige über morgige Müllabfuhr
  trigger:
  - platform: state
    entity_id: binary_sensor.srhh_blaue_papiertonne_1d
    to: '''on'''
  condition: []
  action:
  - service: notify.mobile_app_sm_g955f
    data:
      title: Müllabfuhr
      message: Die blaue Tonne rausstellen - morgen ist Abholung
      data:
        group: Müllabfuhr
        tag: blaue-Tonne
        sticky: 'true'
        actions:
        - action: HEATING_ON
          title: Test1
        - action: HEATING_OFF
          title: Später erinnern
  - service: notify.mobile_app_philipp_iphone8
    data:
      title: Müllabfuhr
      message: Die blaue Tonne rausstellen - morgen ist Abholung
      data:
        push:
          thread-id: Müllabfuhr
          category: mullabfuhr
        apns_headers:
          apns-collapse-id: blaue-Tonne
  mode: single
