#====================================
#== Default configuration of Home Assistant
#====================================
default_config:


frontend:
  themes: !include_dir_merge_named themes

#====================================
#=== Favicon and Page title
#====================================
favicon:
  title: BaumAssistant
  icon_path: /local/favicons/

#====================================
#=== Proxy live streams
#====================================
stream:

#====================================
#=== Yahoo Finance (stock market)
#====================================
yahoofinance: !include yahoofinance.yaml

#====================================
#=== Luftdaten: monitor air quality
#====================================
luftdaten:
  sensor_id: 29362
  scan_interval: 3600
  show_on_map: false
  sensors:
    monitored_conditions:
      - P1
      - P2
      - temperature
      - humidity
      - pressure

#====================================
#=== Synology DSM
#====================================
synology_dsm:
  - host: !secret synology_host
    username: !secret synology_username
    password: !secret synology_password
    ssl: false

#====================================
#=== Argon ONE Pi4 Case and Fan
#====================================
spotify:
  client_id:  !secret spotify_id
  client_secret:  !secret spotify_secret

#====================================
#=== Argon ONE Pi4 Case and Fan
#====================================
argon40:

#====================================
#== Netatmo Presence
#====================================
netatmo:
  client_id: !secret netatmo_client_id
  client_secret: !secret netatmo_client_secret

#====================================
#=== BSH (Neff) Home Connect
#====================================
home_connect:
  client_id: !secret home_connect_id
  client_secret: !secret home_connect_secret
  
#====================================
#=== InfluxDB
#====================================
influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: !secret influxdb_database
  username: !secret influxdb_username
  password: !secret influxdb_password
  max_retries: 3
  default_measurement: state

#====================================
#=== Text to speech
#====================================
tts:
  - platform: google_translate


sensor: !include_dir_merge_list sensors/
input_number: !include input_number.yaml
input_select: !include input_select.yaml
input_boolean: !include input_boolean.yaml
binary_sensor: !include binary_sensor.yaml
light: !include lights.yaml
group: !include groups.yaml
script: !include scripts.yaml


zone ui: !include zones.yaml
zone manual: !include_dir_merge_list zones/

# Scenes: created in the UI
scene ui: !include scenes.yaml
# Scenes: created manually in yaml
scene manual: !include_dir_merge_list scenes/

# Automations: created in the UI
automation: !include automations.yaml
# Automations: created manually in yaml
automation manual: !include_dir_merge_list automations/


#====================================
#=== iOS push templates
#====================================
ios:
  push:
    categories:
      - name: Reminder Müllabfuhr
        identifier: 'mullabfuhr'
        actions:
          - identifier: srhh_rausgestellt
            title: 'Erledigt'
            activationMode: 'foreground'
            authenticationRequired: false
            destructive: true
            behavior: 'default'
          - identifier: srhh_3h_reminder
            title: 'Später erinnern'
            activationMode: 'foreground'
            authenticationRequired: false
            destructive: false
            behavior: 'default'


#====================================
#=== HACS: Entities Calendar
#====================================
calendar:
  - platform: entities_calendar
    calendars:
      - name: Müllabfuhr
        entities:
          - entity: sensor.srhh_blaue_papiertonne
            name: blaue Papiertonne
          - entity: sensor.srhh_gelbe_wertstofftonne
            name: gelbe Wertstofftonne/-sack
          - entity: sensor.srhh_gruene_biotonne
            name: grüne Biotonne
          - entity: sensor.srhh_schwarze_restmuelltonne
            name: schwarze Restmülltonne
      - name: Geburtstage
        entities:
          - entity: sensor.anniversary_lynn_baumgarten
            name: Lynn Geburtstag
            start_time:
              timestamp_in_state: true
            end_time:
              timestamp_in_state: true

